name: build-mac-actions
on: [push]
run-name: ${{ github.actor }} is package mac app actions
jobs:
 build:
   runs-on: macos-latest
   steps:
     - uses: actions/checkout@v3
     - uses: subosito/flutter-action@v2
       with:
         channel: 'stable'
         architecture: x64
     - run: flutter pub get
     - run: flutter build macos
     - run: ls ${{ github.workspace }}
     - run: echo "🍏 This job's status is ${{ job.status }}."
     - run: mkdir build/macos/Build/Products/Release/server_box
     - run: mv build/macos/Build/Products/Release/server_box.app build/macos/Build/Products/Release/server_box
     - name: Publish Mac Artefacts
       uses: actions/upload-artifact@v1
       with:
          name: release-mac-app
          path: build/macos/Build/Products/Release/server_box
